// angular/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faArrowRightFromBracket } from '@fortawesome/free-solid-svg-icons';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NgIf } from '@angular/common';

@Component({
    selector: 'app-header',
    standalone: true,
    imports: [FontAwesomeModule, RouterLink, RouterLinkActive, NgIf],
    templateUrl: './header.component.html',
    styleUrl: './header.component.scss',
})
export class HeaderComponent {
    isAuth = false;
    logoutIcon = faArrowRightFromBracket;
}

<header class="shadow-md py-2">
	<div class="container mx-auto grid grid-cols-2 justify-between gap-5 py-4">
		<a href="#">Logo</a>
		<nav *ngIf="isAuth; else isNotAuth" class="flex justify-end">
			<ul class="flex items-center gap-5">
				<li class="text-white/50">
					<a
						routerLink=""
						routerLinkActive="text-white"
						[routerLinkActiveOptions]="{ exact: true }"
						>Home</a
					>
				</li>
				<li class="text-white/50">
					<a routerLink="profile" routerLinkActive="text-white"
						>Profile</a
					>
				</li>
				<li class="text-white/50">
					<button class="flex">
						<fa-icon
							[icon]="logoutIcon"
							class="text-white"
						></fa-icon>
					</button>
				</li>
			</ul>
		</nav>
		<ng-template #isNotAuth>
			<ul class="flex gap-4 items-center ml-auto">
				<li class="text-white/50">
					<a routerLink="signup" routerLinkActive="text-white"
						>Sign Up</a
					>
				</li>
				<li class="text-white/50">
					<a routerLink="login" routerLinkActive="text-white"
						>Login</a
					>
				</li>
			</ul>
		</ng-template>
	</div>
</header>

// client/src/components/Header.tsx
import { FC } from "react";
import { Link, NavLink } from "react-router-dom";
import { FaBtc, FaSignOutAlt } from 'react-icons/fa'

const Header: FC = () => {
    const isAuth: boolean = true
    return (
        <header className="flex items-center justify-between p-4 shadow-sm bg-slate-800 backdrop-blur-sm">
            <Link to='/'>
                <FaBtc size={20} />
            </Link>

            { isAuth && 
                <nav className="ml-auto mr-10">
                    <ul className="flex gap-5 items-center ml-auto mr-10">
                        <li>
                            <NavLink to={'/'} className={({ isActive }) => isActive ? 'text-white' : 'text-white/50'}>Home</NavLink>
                        </li>
                        <li>
                            <NavLink to={'/categories'} className={({ isActive }) => isActive ? 'text-white' : 'text-white/50'}>Categories</NavLink>
                        </li>
                        <li>
                            <NavLink to={'/transactions'} className={({ isActive }) => isActive ? 'text-white' : 'text-white/50'}>Transactions</NavLink>
                        </li>
                    </ul>
                </nav>
            }

            { isAuth ? (
                <button className="btn btn-red">
                    <span>Log Out</span>
                    <FaSignOutAlt />
                </button> ) : (
                    <Link className="py-2 text-white/50 hover:text-white" to={'auth'}>
                        Log In / Sign In
                    </Link>
                )
            }
        </header>
    )
}

export default Header
